### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by yzy6806555** [xingdi-eric-yuan/conv-net-version-3#2]
Mat 
concat(const vector<Mat> &vec){
    int height = vec[0].rows \* vec[0].cols;
    int width = vec.size();
    Mat res = Mat::zeros(height, width, CV_64FC3);
    for(int i = 0; i < vec.size(); i++){
        Rect roi = Rect(i, 0, 1, height);
        Mat subView = res(roi);
        Mat ptmat = vec[i].reshape(0, height);
        ptmat.copyTo(subView);
    }
    return res;
}

i think this function is Invalid function, the result 'res' is always zeors!

**Comment by xingdi-eric-yuan** [comment]
Hi yangzhenyu, 

I think it does work, you can test the following code:

int main(){
    Mat _zeros = Mat::zeros(9, 9, CV_64FC1);
    cout<<"zeros --- "<<endl;
    cout<<" "<<_zeros<<endl;
    Rect roi = Rect(0, 0, 1, _zeros.rows);
    Mat subView = _zeros(roi);
    Mat _ones = Mat::ones(3, 3, CV_64FC1);
    Mat tmp = _ones.reshape(0, 9);
    tmp.copyTo(subView);
    cout<<"tmp --- "<<endl;
    cout<<" "<<tmp<<endl;
    cout<<"zeros --- "<<endl;
    cout<<" "<<_zeros<<endl;
    cout<<"roi --- "<<endl;
    cout<<" "<<roi<<endl;
    return 0;
}

Thanks!

**Comment by zhxfl** [comment]
// get average
Mat average = trainX[0] / (trainX.size() + testX.size());
    for(int i = 1; i < trainX.size(); i++)
        average += trainX[i] / (trainX.size() + testX.size());
    for(int i = 0; i < testX.size(); i++)
        average += testX[i] / (trainX.size() + testX.size());
    // subtract average
    for(int i = 0; i < trainX.size(); i++)
        trainX[i] -= average;
    for(int i = 0; i < testX.size(); i++)
        testX[i] -= average;

I use this code just because function concat() will malloc a huge matrix suddenly and the opencv get these Error report:
OpenCV Error: Insufficient memory (Failed to allocate 1228800000 bytes) in cv::O
utOfMemoryError, file D:\Program Files\opencv\sources\modules\core\src\alloc.cpp
, line 52
OpenCV Error: Assertion failed (u != 0) in cv::Mat::create, file D:\Program File
s\opencv\sources\modules\core\src\matrix.cpp, line 408
. .

**Comment by yzy6806555** [comment]
sorry ,I'm not very familiar with this usage of opecv.thank you all!
